### ISSUE TITLE
Asterisk does not start after 2.0.0

### ISSUE THREAD

**Issue by stefanschoemaker** [TECH7Fox/asterisk-hass-addons#127] opened 2022-03-16 19:36 UTC
After updating to 2.0 I cannot connect anymore from the SipJS card, I've restored the backup from 1.3 for now and it is workin again. I also don't see any logs as why it is not working.

**Comment by nanosonde** [comment] 2022-03-16 19:36
```
[cont-init.d] asterisk.sh: exited 0.
[cont-init.d] asterisk_mbox.sh: executing... 
[cont-init.d] asterisk_mbox.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```

**Comment by nanosonde** [comment] 2022-03-16 19:46
I do not see any output from asterisk in the log.
However, when I run a shell in the container I can see that it seems to be running.
When trying to do a `asterisk -rvvvvdddd` it crashed with an illegal instruction.

Wrong architecture packaged?

**Comment by nanosonde** [comment] 2022-03-16 20:14
@TECH7Fox 
Can you give a hint how exactly you created the docker images?

**Comment by felipecrs** [comment] 2022-03-16 20:40
That's it. It gets built automatically by this.

**Comment by nanosonde** [comment] 2022-03-16 21:07
![grafik](https://user-images.githubusercontent.com/2073569/158691145-0a80c6a1-4d5e-425f-81b2-03a1821f7ada.png)

**Comment by nanosonde** [comment] 2022-03-16 21:11
Apparently, it was trying to run an instruction for AVX2 architecture on a system which lacks support for AVX2 instruction set.

![grafik](https://user-images.githubusercontent.com/2073569/158691762-4ff1b9df-fa6d-419d-9425-b4872599dc99.png)

**Comment by felipecrs** [comment] 2022-03-16 21:17
So, it seems that Asterisk isn't built in a portable way. It gets tied to the environment which first built it.

I suspect there is something in the Makefile to tweak this behavior.

For example, that BUILD_NATIVE.

**Comment by nanosonde** [comment] 2022-03-16 21:23
I just verfied that my host CPU supports AVX and AVX2 instructions.
So maybe it is not related not it.

I wonder if BUILD_NATIVE was really set when compiling started. 
When experimenting with it, I also realized that sometimes an enabled option was disabled again.

However, I verfied that the current source works with builing locally on HAOS and prebuilt with the builder provided by HA.

Strange....

**Comment by felipecrs** [comment] 2022-03-16 21:45
> However, I verfied that the current source works with builing locally on HAOS and prebuilt with the builder provided by HA.

Exactly, that's how we didn't catch it in our tests.

**Comment by felipecrs** [comment] 2022-03-17 00:04
Let's try to isolate the issue at least. I'm using amd64 and I can replicate the issue. Is there anyone here who is using ARM?

**Comment by felipecrs** [comment] 2022-03-17 00:18
I can confirm the issue happens when I build and push the image by myself, with or without Docker Buildkit.

```console
docker build asterisk --push
```

From my PC, then HA downloads it and same issue happens.

**Comment by felipecrs** [comment] 2022-03-17 01:28
Fix: https://github.com/TECH7Fox/asterisk-hass-addons/pull/128

**Comment by nanosonde** [comment] 2022-03-17 07:07
@stefanschoemaker Just out of curiosity: What system do you have?

I am using a Synology DS1821+.
Home Assistant is installed in a Synology VMM virtual machine using HA OS.

**Comment by stefanschoemaker** [comment] 2022-03-17 08:47
I'm running a Proxmox host with a Ryzen 3700X and installed HassIO with the original VM image using the following script:
https://raw.githubusercontent.com/Kanga-Who/home-assistant/master/hassos_install.sh

**Comment by felipecrs** [comment] 2022-03-17 12:06
I have an Intel J4125 Gemini Lake btw.

**Comment by felipecrs** [comment] 2022-03-17 12:21
v2.0.1 is out, with a fix for this. Could someone other than me test and confirm?

**Comment by nanosonde** [comment] 2022-03-17 12:37
Yes, I will test it right now.

**Comment by nanosonde** [comment] 2022-03-17 12:51
I have removed the addon and reinstalled with everyhting clean.

Unfortunately, it does not seem to work properly during startup.

![grafik](https://user-images.githubusercontent.com/2073569/158812060-67d74506-f96f-497d-8645-738005804808.png)

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: Asterisk
 PBX server for SIP devices like doorbells and phones
-----------------------------------------------------------
 Add-on version: 2.0.1
 You are running the latest version of this add-on.
 System: Home Assistant OS 7.5  (amd64 / qemux86-64)
 Home Assistant Core: 2022.3.5
 Home Assistant Supervisor: 2022.03.4
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to DEBUG
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] asterisk.sh: executing... 
[13:47:21] INFO: Configuring certificate...
[13:47:21] INFO: Using existing certificate as 'generate_ssl_certificate' is disabled...
[13:47:21] INFO: Configuring Asterisk...
sending incremental file list
./
sent 2,634 bytes  received 20 bytes  5,308.00 bytes/sec
total size is 693,679  speedup is 261.37
[cont-init.d] asterisk.sh: exited 0.
[cont-init.d] asterisk_mbox.sh: executing... 
[cont-init.d] asterisk_mbox.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[13:47:22] INFO: Starting Asterisk...
[services.d] done.
[cmd] /bin/bash exited 0
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
/usr/lib/bashio/config.sh: line 56: printf: write error: Broken pipe
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

**Comment by nanosonde** [comment] 2022-03-17 12:57
I have started the container manually with a shell. 
I am able to start asterisk without any crash now.

**Comment by nanosonde** [comment] 2022-03-17 14:15
So something seems to wrong with the init system.
Any new ideas?

**Comment by nanosonde** [comment] 2022-03-17 14:45
This the command start the container starts:
```
/init /bin/bash -euxo pipefail -c '#(nop) ' 'ENV ASTERISK_VERSION=18.10.1'
```

Is this supposed to be like that?

Most other containers with S6 just do:
```
/init
```

**Comment by felipecrs** [comment] 2022-03-17 14:54
Checking

**Comment by nanosonde** [comment] 2022-03-17 15:42
This guy here had the same issue: https://community.home-assistant.io/t/help-figuring-out-why-my-addon-wont-start/326976

It seems he solved it by addig this in his addon docker file:
https://github.com/YoloDev/hass-addons/blob/main/enet/Dockerfile#L25-L26

**Comment by felipecrs** [comment] 2022-03-17 16:27
Confirmed that it solves the issue:

```console
❯ docker run --pull=always --rm -d ghcr.io/tech7fox/amd64-addon-asterisk:2.0.1 && docker ps | grep asterisk
fa8a0664d824   ghcr.io/tech7fox/amd64-addon-asterisk:2.0.1   "/init /bin/bash -eu…"   Less than a second ago   Up Less than a second             sweet_villani

❯ docker run --pull=always --rm -d ghcr.io/tech7fox/amd64-addon-asterisk:2.0.2 && docker ps | grep asterisk
df7969e82321   ghcr.io/tech7fox/amd64-addon-asterisk:2.0.2   "/init"   1 second ago    Up Less than a second             magical_nash
```

**Comment by felipecrs** [comment] 2022-03-17 16:30
> @felipecrs Could you please explain why enabling buildkit solves the issue? I would like to learn something new… 😉

Idk why, but buildkit produces different (more modern and less cluttered) image manifests. In the manifest, you can see the CMD being set. So, I had the idea to build with buildkit (which is the default nowadays, the addon-builder is probably lagging behind).

I can't explain why exactly the issue happened.

**Comment by felipecrs** [comment] 2022-03-17 16:36
I just installed 2.0.2 in my HA and it's working. Can someone else confirm?

**Comment by nanosonde** [comment] 2022-03-17 16:57
Confirmed. It is working now!

Good job!

**Closed** 2022-03-17 16:58 UTC
Labels: help wanted
