### ISSUE TITLE
BUG: Can't edit the allowed networks for Manager login

### ISSUE THREAD

**Issue by netsoft-ruidias** [TECH7Fox/asterisk-hass-addons#309] opened 2024-02-22 18:01 UTC
I found a bug...

I had an error, Manager "admin' was unable to login (DENIED) 

After some digging, I found out that I should edit the `manager.conf` file, so I followed the docs and created a new file inside the `custom` folder, based in the original inside `default` and with the new content, like this:

```diff
(...)

[admin]
secret = --REDACTED--
deny = 0.0.0.0/0.0.0.0
-permit = 127.0.0.1/255.255.255.0
+permit = 192.168.1.2/255.255.255.0
(...)
```

But then I realized that my changes was not taking effect because the file was constantly rewritten at startup by `/etc/cont-init.d/asterisk.sh`, here:
```sh
bashio::var.json \
    password "$(bashio::config 'ami_password')" |
    tempio \
        -template "${tempio_dir}/manager.conf.gtpl" \
        -out "${etc_asterisk}/manager.conf"
```

The script is rewriting the file in order to update the `ami_password` field and delete my changes...

Can you please find a way to persist my changes to prevent them from being lost?

**Comment by felipecrs** [comment] 2024-02-22 18:25
Just place the file at /config/asterisk/custom/manager.conf, which will always have precedence.

https://github.com/TECH7Fox/asterisk-hass-addons/blob/main/asterisk/DOCS.md#configuring-asterisk

**Comment by netsoft-ruidias** [comment] 2024-02-22 19:24
@felipecrs that's exactly what I did, maybe it wasn't clear.
By placing at `/config/asterisk/custom/manager.conf` the file is rewritten whenever the container is restarted.

**Comment by felipecrs** [comment] 2024-02-22 19:38
I see. This feature was introduced in v3:

> - You can now override/customize any Asterisk files (previously, the auto-generated Asterisk files could not be overriden).

https://github.com/TECH7Fox/asterisk-hass-addons/blob/main/asterisk/CHANGELOG.md#300

I'll try to reproduce it later.

**Comment by felipecrs** [comment] 2024-02-22 19:41
https://github.com/TECH7Fox/asterisk-hass-addons/assets/29582865/ae17d7d1-6fc0-45e8-81b3-db01fd90bb38

It's working fine for me. The add-on may take a few seconds after initialization to properly replace the file.

**Comment by netsoft-ruidias** [comment] 2024-02-23 10:28
Thanks @felipecrs , I learned something new today...

1. I'm using `docker-compose` to initialize all my containers and services (I have a cluster);
2. If I use `docker-compose down` and then `docker-compose up -d` then everything works as expected and the document is not changed back to defaults;
3. But I was using `docker-compose restart asterisk` and in this case the file IS ACTUALLY rewritten with the default.

What I didn't know, and learned today, is that `down`+`up` commands works differently than `restart`, in docker.

I was using `restart` for convenience, because as I was adjusting the asterisk settings, so I wanted to restart only the Asterisk container with the new values, but without necessarily having to shut down my entire cluster, which is what happens with "down".

Here's a note for the future, if you're having the same problem, don't use `docker-compose restart [...]`

However, I will not close this thread (I leave that to the owner's discretion) as I believe there is room for improvement
cc: @TECH7Fox

**Comment by felipecrs** [comment] 2024-02-23 13:02
I see. This is actually normal for this image. We use s6-overlay and the initialization scripts are executed as part of cont-init.d. cont-init.d only runs once per container, and that's why restart doesn't trigger it.

This is completely fine for add-on users, because when you click Restart, Supervisor would in fact destroy the container and create another.

And yeah, it would not hurt having this explained in the documentation.

**Comment by felipecrs** [comment] 2024-02-23 15:57
I'm closing this for now, but PRs to improve documentation are always welcome.

**Comment by felipecrs** [comment] 2024-03-02 22:54
by @netsoft-ruidias at https://github.com/TECH7Fox/asterisk-hass-addons/issues/310:

> I'm reopening [this issue](https://github.com/TECH7Fox/asterisk-hass-addons/issues/309) again (I can't reopen the original) because I have news and there is actually a BUG that must be fixed.
> 
> Note
> 
> For more context on what's going on, take a look at the original issue: #309
> 
> 1. If I use `docker-compose down` and then `docker-compose up -d` then everything works as expected and the file is not changed back to defaults;
> 2. If I use `docker-compose restart` the file IS ACTUALLY rewritten with the default values, losing all customizations;
> 3. If I have a power outage, when the container starts, the file IS ACTUALLY rewritten with the default values, losing all customizations.
> 
> ✔️ The first point is (obviously) not a problem because it is the expected behavior ✖️ The second point is a problem but there is a workaround, don't run that command ❌ The third point is a MAJOR problem and happens because docker compose is a service that starts at machine startup, and the container definition declares `restart: unless-stopped`
> 
> For context, this is my docker-compose yaml:
> 
> ```yaml
> version: '3.9'
> services:
>   (...)other services(...)
> 
>   asterisk:
>     container_name: asterisk
>     image: ghcr.io/tech7fox/asterisk-hass-addon:main
>     build:
>       context: ./asterisk
>     tty: true
>     network_mode: host
>     environment:
>       TZ: 'Europe/Lisbon'
>       # Required to get the list of persons from Home Assistant
>       HA_TOKEN: "--REDACTED--"
>       HA_URL: 'https://xxxx.xxx.com'
>     dns:
>       - 192.168.1.2
>       - 8.8.8.8
>       - 8.8.4.4
>     volumes:
>       - /srv/homeassistant/config/asterisk:/config
>       - /srv/homeassistant/config/www/sounds:/media
>       - /srv/homeassistant/config/ssl:/ssl
>     restart: unless-stopped
> 
>   (...)other services(...)
> ```

**Comment by felipecrs** [comment] 2024-03-02 22:57
I see your point.

A note to myself or anyone else looking into this: it looks like s6-overlay is not executing [`cont-init.d`](https://github.com/TECH7Fox/asterisk-hass-addons/blob/main/asterisk/rootfs/etc/cont-init.d/asterisk.sh) on container restart, but I don't know if this is intended or not.

**Comment by OnFreund** [comment] 2024-04-21 16:41
I'm also seeing this - there's no way to persist my changes to `manager.conf` (and I'm guessing it also applies to every generated config file, with the exception of the sip configuration files that have separate `-custom` files).

**Comment by felipecrs** [comment] 2024-04-21 16:48
@OnFreund workaround is to delete the container and recreate it rather than just restarting it.

**Comment by OnFreund** [comment] 2024-04-21 16:58
Wouldn't deleting the container execute `cont-init.d` again and overwrite my changes?

**Comment by felipecrs** [comment] 2024-04-21 17:06
cont-init.d will never delete /config/asterisk/custom.

**Comment by felipecrs** [comment] 2024-04-21 17:16
If you are using docker compose, you can just use `docker compose up --force-recreate`,

**Comment by OnFreund** [comment] 2024-04-21 17:16
> cont-init.d will never delete /config/asterisk/custom.

It does - that's exactly the problem we're describing here. I think it's because of the links - it's editing the file in `/etc/asterisk/`, which is a link to the file in `/config/asterisk/custom/`, thereby overwriting the latter.

**Comment by felipecrs** [comment] 2024-04-21 17:18
Not sure if I understood. Deleting a link (/etc/asterisk/yourfile) doesn't delete the original file (/config/asterisk/custom/yourfile).

**Comment by OnFreund** [comment] 2024-04-21 17:18
It doesn't delete the file, it overwrites it

**Comment by felipecrs** [comment] 2024-04-21 17:19
How come? cont-init.d never writes anything to /config/asterisk/custom. It only writes to /config/asterisk/default.

**Comment by OnFreund** [comment] 2024-04-21 17:20
> How come? cont-init.d never writes anything to /config/asterisk/custom. It only writes to /config/asterisk/default.

It doesn't write to `/config/asterisk/default/`, it writes to `/etc/asterisk/`
https://github.com/TECH7Fox/asterisk-hass-addons/blob/9044fbae5b57b12c27f834769fbfd0ff18b57f3f/asterisk/rootfs/etc/cont-init.d/asterisk.sh#L110

**Comment by felipecrs** [comment] 2024-04-21 17:20
Surely it writes to /etc/asterisk, what's the problem with that?

**Comment by OnFreund** [comment] 2024-04-21 17:21
That `/etc/asterisk/manger.conf` is a link to `/config/asterisk/custom/manager.conf`, so the latter gets overwritten.

**Comment by felipecrs** [comment] 2024-04-21 17:22
You mean /etc/asterisk/manger.conf gets overwritten by a link to /config/asterisk/custom/manager.conf?

**Comment by OnFreund** [comment] 2024-04-21 17:24
No no.
1. Create `/config/asterisk/custom/manager.conf`
2. `/etc/asterisk/manger.conf` gets turned to a link to `/config/asterisk/custom/manager.conf`
3. Restart the container
4. Tempio executes, trying to overwrite `/etc/asterisk/manger.conf`
5. Because it's just a link to `/config/asterisk/custom/manager.conf`, the latter is the file that actually gets overwritten
6. Your changes are lost

**Comment by felipecrs** [comment] 2024-04-21 17:26
Oh, you nailed it. That's what's causing this issue then.

Anyway, that's why recreating the container rather than restart it will solve the problem: there will be no symlink when tempio executes.

**Comment by OnFreund** [comment] 2024-04-21 17:28
Oh, interesting. However, as @netsoft-ruidias mentioned, we can't control this during a reboot or restart of the docker service.
I can avoid calling `docker compose restart`, but I can't avoid the other scenarios, and the impact is quite severe - you lose all of your custom config.

**Comment by OnFreund** [comment] 2024-04-21 17:31
I think a solution could be:
1. The target for tempio is always `/config/asterisk/default/`
2. `/etc/asterisk/manager.conf` (and same goes for other files) symlinks to `/config/asterisk/custom/manager.conf` if it exists, otherwise to `/config/asterisk/default/manager.conf`

**Comment by felipecrs** [comment] 2024-04-21 17:35
I think #323 is a simpler solution.

**Comment by OnFreund** [comment] 2024-04-21 17:37
Cool. Hope we can get a release out soon

**Closed** 2024-04-21 17:41 UTC

**Comment by felipecrs** [comment] 2024-04-21 17:56
@OnFreund @netsoft-ruidias please try again with 4.2.1.

**Comment by netsoft-ruidias** [comment] 2024-04-21 18:47
@felipecrs just did.
I'll let you know the results as soon as I run some tests.
Thanks

**Comment by OnFreund** [comment] 2024-04-21 19:10
I can confirm it's fixed (as well as the `friendly_name` instead of `id` fix)
